dist: trusty
# use temporarily the previous version of Trusty image
# until Travis fixes issue with mounting permissions
group: deprecated-2017Q2

sudo: required

language: c

env:
  matrix:
    - AUTOGENSOURCES=1 PUSH_IMAGE=1 COVERAGE=1 OS=ubuntu OS_VER=17.04

before_install:
  - export HOST_WORKDIR=`pwd`
  - export GITHUB_REPO=pmem/pmemfile
  - export DOCKERHUB_REPO=pmem/pmemfile
  - export EXTRA_DOCKER_ARGS=-t
  - cd utils/docker
  - ./prepare-environment.sh
  - ./pull-or-rebuild-image.sh
  - if [[ -f push_image_to_repo_flag ]]; then PUSH_THE_IMAGE=1; fi
  - rm -f push_image_to_repo_flag

script:
  - ./build.sh

after_success:
  - if [[ $PUSH_THE_IMAGE -eq 1 ]]; then images/push-image.sh $OS-$OS_VER; fi
